{
  "hash": "00864c58d09d765b470820cd13493ef9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"More data wrangling and visualization\"\nsubtitle: \"Workshop 1, Module 4\"\nformat: qmdrslides-revealjs\neditor: source\nexecute:\n  echo: true\n  message: false\n  warning: false\n---\n\n\n\n## Goals for this module\n\nBy the end of this module you can:\n\n- name what a row represents *before and after* every verb in a pipeline\n- collapse a table to one row per group with `group_by` + `summarise`\n- attach data from another table with `left_join`\n- filter by membership in another table with `semi_join`\n- reshape between long and wide with `pivot_longer` and `pivot_wider`\n- pick the right plot for a distribution (histogram, boxplot, quasirandom, violin)\n- layer raw observations under a computed summary in one figure\n\n## Module 3 preserved row meaning. Module 4 changes it.\n\nModule 3's verbs all kept \"what a row represents\" the same: `filter` drops rows but each remaining row still means the same thing; `mutate` adds columns; `arrange` reorders.\n\nModule 4's verbs change it. Or sometimes don't. You have to know which.\n\nThe whole module asks one question on every slide: **what does a row represent now?**\n\n## The through-line: `table_02`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_02\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 132 × 6\n   pid    time_point arm     nugent_score crp_blood    ph\n   <chr>  <chr>      <chr>          <dbl>     <dbl> <dbl>\n 1 pid_01 baseline   placebo            8      0.44   5.7\n 2 pid_01 week_1     placebo            7      1.66   5.2\n 3 pid_01 week_7     placebo            7      1.44   5.4\n 4 pid_02 baseline   placebo            7      1.55   5.2\n 5 pid_02 week_1     placebo            7      0.75   4.8\n 6 pid_02 week_7     placebo            4      1.17   4.2\n 7 pid_03 baseline   placebo            6      1.78   4.8\n 8 pid_03 week_1     placebo           10      0.57   5.3\n 9 pid_03 week_7     placebo            7      1.79   5.2\n10 pid_04 baseline   placebo            5      1.76   4.8\n# ℹ 122 more rows\n```\n\n\n:::\n:::\n\n\n132 rows. *Row = participant-visit* (44 participants × 3 visits).\n\nWe will transform this same table through the next 18 slides. Watch what each verb does to the row count, and to what a row represents.\n\n## `group_by` is a state change, not a shape change\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_02 |> group_by(pid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 132 × 6\n# Groups:   pid [44]\n   pid    time_point arm     nugent_score crp_blood    ph\n   <chr>  <chr>      <chr>          <dbl>     <dbl> <dbl>\n 1 pid_01 baseline   placebo            8      0.44   5.7\n 2 pid_01 week_1     placebo            7      1.66   5.2\n 3 pid_01 week_7     placebo            7      1.44   5.4\n 4 pid_02 baseline   placebo            7      1.55   5.2\n 5 pid_02 week_1     placebo            7      0.75   4.8\n 6 pid_02 week_7     placebo            4      1.17   4.2\n 7 pid_03 baseline   placebo            6      1.78   4.8\n 8 pid_03 week_1     placebo           10      0.57   5.3\n 9 pid_03 week_7     placebo            7      1.79   5.2\n10 pid_04 baseline   placebo            5      1.76   4.8\n# ℹ 122 more rows\n```\n\n\n:::\n:::\n\n\nSame 132 rows. *Row meaning unchanged.* What changed is that subsequent verbs now act *per group*.\n\n## `summarise` collapses each group to one row\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_02 |>\n  group_by(pid) |>\n  summarise(\n    mean_ph = mean(ph),\n    mean_nugent = mean(nugent_score)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 44 × 3\n   pid    mean_ph mean_nugent\n   <chr>    <dbl>       <dbl>\n 1 pid_01    5.43        7.33\n 2 pid_02    4.73        6   \n 3 pid_03    5.1         7.67\n 4 pid_04    5.1         7   \n 5 pid_05    3.87        4.33\n 6 pid_06    5.3         8.67\n 7 pid_07    5.07        6.33\n 8 pid_08    5.07        7   \n 9 pid_09    4.23        4   \n10 pid_10    3.77        3   \n# ℹ 34 more rows\n```\n\n\n:::\n:::\n\n\n132 → 44 rows. *Row = participant.* Visits collapsed.\n\n## Different grouping, different row meaning\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_02 |>\n  group_by(arm, time_point) |>\n  summarise(mean_ph = mean(ph))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n# Groups:   arm [2]\n  arm       time_point mean_ph\n  <chr>     <chr>        <dbl>\n1 placebo   baseline      5.09\n2 placebo   week_1        4.82\n3 placebo   week_7        4.73\n4 treatment baseline      4.54\n5 treatment week_1        3.51\n6 treatment week_7        3.90\n```\n\n\n:::\n:::\n\n\n132 → 6 rows. *Row = arm-timepoint.* Same starting data, different grouping, different row meaning.\n\n## You picked what a row means\n\nThe verb didn't decide.\n\nWhen you wrote `group_by(pid)`, the row collapsed to a participant.\n\nWhen you wrote `group_by(arm, time_point)`, it collapsed to an arm-timepoint cell.\n\nThe grouping is the design choice that decides what a row will mean after `summarise`.\n\n## Quick check {.your-turn}\n\nWhat does each row represent, and how many rows, after:\n\n```r\ntable_01 |>\n  group_by(smoker) |>\n  summarise(n = n(), mean_age = mean(age))\n```\n\nPredict before the reveal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountdown::countdown(1, top = 0)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_24bc5122\" minutes=\"1\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## `group_by` + `mutate` — same rows, derived by group\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_02 |>\n  group_by(arm) |>\n  mutate(rank_ph_within_arm = rank(ph)) |>\n  select(pid, arm, ph, rank_ph_within_arm) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n# Groups:   arm [1]\n  pid    arm        ph rank_ph_within_arm\n  <chr>  <chr>   <dbl>              <dbl>\n1 pid_01 placebo   5.7               68  \n2 pid_01 placebo   5.2               48  \n3 pid_01 placebo   5.4               61  \n4 pid_02 placebo   5.2               48  \n5 pid_02 placebo   4.8               27.5\n6 pid_02 placebo   4.2                7.5\n```\n\n\n:::\n:::\n\n\nStill 132 rows, *row = participant-visit.* The new column is computed within each arm. `group_by` doesn't always collapse; the verb after it decides.\n\n## `left_join` — the mutating join\n\n`left_join` adds columns from a second table by matching on a key. *Same row meaning, same row count* (when the join is well-formed).\n\n![](images/join.svg)\n\n## `left_join` — demo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nper_person <- table_02 |>\n  group_by(pid) |>\n  summarise(mean_ph = mean(ph), mean_nugent = mean(nugent_score))\n\nper_person |> left_join(table_01, by = \"pid\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 44 × 8\n   pid    mean_ph mean_nugent arm       smoker       age education         sex  \n   <chr>    <dbl>       <dbl> <chr>     <chr>      <dbl> <chr>             <lgl>\n 1 pid_01    5.43        7.33 placebo   non-smoker    26 grade 10-12, mat… FALSE\n 2 pid_02    4.73        6    placebo   smoker        33 grade 10-12, mat… FALSE\n 3 pid_03    5.1         7.67 placebo   smoker        30 post-secondary    FALSE\n 4 pid_04    5.1         7    placebo   non-smoker    34 grade 10-12, not… FALSE\n 5 pid_05    3.87        4.33 treatment non-smoker    29 grade 10-12, mat… FALSE\n 6 pid_06    5.3         8.67 placebo   smoker        34 post-secondary    FALSE\n 7 pid_07    5.07        6.33 placebo   non-smoker    31 grade 10-12, not… FALSE\n 8 pid_08    5.07        7    placebo   smoker        30 grade 10-12, not… FALSE\n 9 pid_09    4.23        4    treatment non-smoker    35 grade 10-12, not… FALSE\n10 pid_10    3.77        3    treatment non-smoker    32 less than grade 9 FALSE\n# ℹ 34 more rows\n```\n\n\n:::\n:::\n\n\n44 rows in, 44 rows out. *Row = participant* (unchanged). New columns: `arm`, `smoker`, `age`, `education`, `sex`.\n\n## `semi_join` — the filtering join\n\n`semi_join` keeps rows in the left table that have a match in the right table. *No new columns.* Same row meaning, fewer rows.\n\n![](images/joins-venn.svg)\n\n## `semi_join` — demo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmokers <- table_01 |> filter(smoker == \"smoker\")\n\nper_person |> semi_join(smokers, by = \"pid\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 17 × 3\n   pid    mean_ph mean_nugent\n   <chr>    <dbl>       <dbl>\n 1 pid_02    4.73        6   \n 2 pid_03    5.1         7.67\n 3 pid_06    5.3         8.67\n 4 pid_08    5.07        7   \n 5 pid_11    4.47        4   \n 6 pid_14    4.87        6.33\n 7 pid_18    3.93        4.33\n 8 pid_20    4.8         5.67\n 9 pid_25    4.1         3   \n10 pid_26    4.47        3.67\n11 pid_27    4.97        6.67\n12 pid_29    4.6         4.67\n13 pid_33    3.83        3   \n14 pid_38    4.8         5.67\n15 pid_41    4.03        3.33\n16 pid_42    4.77        6   \n17 pid_43    4.3         6   \n```\n\n\n:::\n:::\n\n\n*Row = participant* (unchanged). Rows that aren't smokers are dropped.\n\n## Watch out — many-to-many joins multiply rows\n\nIf both sides have duplicate keys, the join multiplies rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleft <- tibble(id = c(1, 1, 2), x = c(\"a\", \"b\", \"c\"))\nright <- tibble(id = c(1, 1, 2), y = c(\"p\", \"q\", \"r\"))\nleft |> left_join(right, by = \"id\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n     id x     y    \n  <dbl> <chr> <chr>\n1     1 a     p    \n2     1 a     q    \n3     1 b     p    \n4     1 b     q    \n5     2 c     r    \n```\n\n\n:::\n:::\n\n\n3 + 3 = ... 5 rows. A well-formed join from a tidy left table should *not* change your row count. If it does, your key isn't unique somewhere.\n\n## Quick check {.your-turn}\n\nWhat does each row represent, and how many rows, after:\n\n```r\ntable_02 |>\n  left_join(table_01, by = c(\"pid\", \"arm\"))\n```\n\n(Hint: `arm` appears in both tables. Does that change anything?)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountdown::countdown(1, top = 0)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_f5de19b1\" minutes=\"1\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"top:0;right:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## `pivot_longer` — from wide to long\n\nEach measurement column becomes a row.\n\n![](images/pivot.svg)\n\n## `pivot_longer` — demo\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_02 |>\n  pivot_longer(\n    cols = c(ph, nugent_score, crp_blood),\n    names_to = \"measurement\",\n    values_to = \"value\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 396 × 5\n   pid    time_point arm     measurement  value\n   <chr>  <chr>      <chr>   <chr>        <dbl>\n 1 pid_01 baseline   placebo ph            5.7 \n 2 pid_01 baseline   placebo nugent_score  8   \n 3 pid_01 baseline   placebo crp_blood     0.44\n 4 pid_01 week_1     placebo ph            5.2 \n 5 pid_01 week_1     placebo nugent_score  7   \n 6 pid_01 week_1     placebo crp_blood     1.66\n 7 pid_01 week_7     placebo ph            5.4 \n 8 pid_01 week_7     placebo nugent_score  7   \n 9 pid_01 week_7     placebo crp_blood     1.44\n10 pid_02 baseline   placebo ph            5.2 \n# ℹ 386 more rows\n```\n\n\n:::\n:::\n\n\n132 → 396 rows. *Row = participant-visit-measurement.* Useful for faceted plots — we'll use this in Exercise 2.\n\n## `pivot_wider` — from long to wide\n\nThe inverse: one row per entity with the previously-long values spread out as columns.\n\n![](images/pivot.svg)\n\n## `pivot_wider` — demo\n\n\n::: {.cell}\n\n```{.r .cell-code}\narm_timepoint <- table_02 |>\n  group_by(arm, time_point) |>\n  summarise(mean_ph = mean(ph))\n\narm_timepoint |>\n  pivot_wider(\n    names_from = time_point,\n    values_from = mean_ph\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n# Groups:   arm [2]\n  arm       baseline week_1 week_7\n  <chr>        <dbl>  <dbl>  <dbl>\n1 placebo       5.09   4.82   4.73\n2 treatment     4.54   3.51   3.90\n```\n\n\n:::\n:::\n\n\n6 → 2 rows. *Row = arm.* Three new columns, one per visit. Useful for table-style display.\n\n## Exercise 1 {.your-turn}\n\nOpen `notebooks/04-wrangling.qmd` in your Codespace.\n\n<br>\n\nGroup A: agentic. Group B: manual.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountdown::countdown(30)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_1b093f72\" minutes=\"30\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}