{
  "hash": "9fd34df87c1728e149ed7ae99efe5d1d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modeling and Uncertainty\"\nsubtitle: \"<em>Building models for biological data</em>\"\nauthor: Kris Sankaran and Marothi Peter Letsoalo\nbibliography: references.bib\ncsl: https://www.zotero.org/styles/vancouver\nformat:\n    qmdrslides-revealjs:\n        fig-align: center\n        include-in-header:\n            text: |\n                <style>\n                .reveal .slides section img {\n                    display: block;\n                    margin-left: auto;\n                    margin-right: auto;\n                }\n                </style>\neditor_options:\n  chunk_output_type: inline\n\nexecute:\n  cache: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n## {data-menu-title=\"Website Link\" style=\"text-align: center\"}\n\n\\\n\\\n\\\n\n:::{.r-fit-text}\nWorkshop materials are at:\n\n[https://elsherbini.github.io/durban-data-science-for-biology/](https://elsherbini.github.io/durban-data-science-for-biology/)\n:::\n\n## {data-menu-item=\"Goals\"}\n\n### Goals for this session {style=\"font-size: 2em; text-align: center\"}\n\n:::{.incremental style=\"font-size: 1.1em\"}\n\n1. Distinguish between the \"large\" and \"small\" worlds of modeling.\n\n2. Compare biostatistical models and explain when they apply.\n\n3. Use R to estimate models and know how to explain the output.\n\n4. Diagnose and address model failures.\n:::\n\n# Part 1: What is a Model?\n\n## Let's start with a picture\n\n- The plots below show IL-1a concentration from our workshop luminex dataset.\n\n- Notice the variation across people and a possible treatment effect at the post-treatment visit.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-il1-1.png){width=768}\n:::\n:::\n\n\n## Discussion {.your-turn}\n\nImagine running the study again, keeping the recruitment and experimental protocols as similar as possible. Make two lists:\n\n::: incremental\n- Aspects of the plots that you think *will still be true* in the new experiment.\n- Aspects of the plots that you think *will change*.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-copy-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_28f7a2fa\" minutes=\"5\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n## A statistical model\n\n> A statistical model is a simplified description of how the data were generated, the \"data story.\"\n\n- Model parameters let us answer scientific questions, like how a treatment affects outcomes.\n\n- We observe just one realization of the data generating process -- things could have turned out differently if we ran the study again.\n\n## Large vs. small worlds\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Large world**\n\n- Where the data were actually gathered\n- Complex, influenced by factors we never observed\n- Hard to carry out controlled interventions\n:::\n::: {.column width=\"50%\"}\n**Small world**\n\n- Inside the statistical model\n- Logically consistent with precisely stated assumptions\n- Allows hypothetical interventions and quantifies uncertainty\n:::\n:::\n\nThere will always be a gap between the two worlds. That gap is itself a source of uncertainty not captured by the model.\n\n## Large Worlds\n\nA dataset is like a photograph of a biological system, but it develops slowly\nand is more error prone.\n\n![](images/malaria.jpeg)\n\n## Large Worlds\n\nA dataset is like a photograph of a biological system, but the snapshot takes longer to generate and is more error prone.\n\n![](images/luminex_overview.png)\n\n## Large Worlds\n\nA dataset is like a photograph of a biological system, but the snapshot takes longer to generate and is more error prone.\n\n![](images/cytometry_csv.png)\n\n## Small Worlds\n\n- The small-world model summarizes what would stay true if the experiment were repeated.\n\n- It encodes a _data generating process_ that lets us simulate new data with the experiment's key features, without memorizing every sample.\n\n![](images/example_small_worlds.png)\n\n## Modeling Checklist\n\n::: {.incremental style=\"font-size: 0.95em\"}\n1. **Biological Question.** What real-world questions do you want to answer?\n\n2. **Plot the Data.** What does the outcome look like? Do you notice relationships with other variables?\n\n3. **Working Assumptions.** Make a small-world story for how the data were generated. This is the initial statistical model.\n\n4. **Model Checks.** Use simulation and diagnostics to check whether the model captures patterns we see in the real data.\n\n5. **Revised Models.** Revise until the model provides a good match. Use this to answer the original question.\n:::\n\n# Part 2: A Tour through the Model Zoo\n\n## Why a zoo?\n\nEach type of statistical model is designed for a different kind of data or biological question.\n\nKnowing different model \"species\" lets you adapt to whatever data or questions\nyou encounter.\n\n::: {style=\"font-size: 0.9em\"}\n_Today's tour:_\n\n- **Bernoulli / Binomial** — binary outcomes\n- **Poisson** — count outcomes\n- **Linear regression** — continuous outcomes\n- **Variations** — multiple predictors, mixed effects, interactions\n:::\n\n## Bernoulli and Binomial Models\n\nThese models apply when outcomes fall into **two groups**.\n\n- Heads vs. tails\n- Infected vs. not infected\n- Responder vs. non-responder\n- CD3- cell vs. not CD3- cell\n\n::: {.fragment}\nThe **Bernoulli** is for *individual outcomes*, the **Binomial** applies to their *totals*\n:::\n\n## Bernoulli and Binomial Models\n\nThe raw data come from two classes, and we want their relative probabilities.\n\n![](images/bernoulli_circles.png)\n\n## Bernoulli and Binomial Models\n\nThe raw data come from two classes, and we want their relative probabilities.\n\n![](images/bernoulli_binomial_comparison.png)\n\n## Model Covariates\n\nThe outcome probabilities can depend on sample-level covariates.\n\n![](images/bernoulli_sizes_covariate.png)\n\n## Model Covariates\n\nThe outcome probabilities can depend on sample-level covariates.\n\n![](images/bernoulli_sizes_curve.png)\n\n## Small-world\n\n- The small-world model summarizes the relationship between covariates and response using this curve.\n\n- The data generating process not only samples the correct frequencies but maintains the covariate-response relationship.\n\n![](images/bernoulli_sizes_curve.png)\n\n## Example data story\n\n- **Response $y$**: Who does (1) or doesn't (0) get infected during an outbreak?\n\n- **Covariates $x$**: Some people have larger social networks than others.\n\n- **Story**: More social contact → higher probability of infection.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-bernoulli-1.png){width=120%}\n:::\n:::\n\n\n## Infection data\n\n- Each row corresponds to a person\n- The outcome takes one of two values\n\n\n::: {#tbl-infections-sample .cell}\n\n```{.r .cell-code}\ninfections |>\n    select(sample_id, social_contact, infected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 100 × 3\n   sample_id social_contact infected\n   <chr>              <dbl>    <dbl>\n 1 sample_1          0.748         1\n 2 sample_2          0.379         0\n 3 sample_3          0.483         0\n 4 sample_4          0.813         0\n 5 sample_5          0.670         0\n 6 sample_6          0.400         0\n 7 sample_7          0.0899        0\n 8 sample_8          0.611         1\n 9 sample_9          0.935         0\n10 sample_10         0.849         1\n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\n## Fitting with `glm`\n\nThe `glm` function has three arguments:\n\n::: incremental\n- `formula`: written `y ~ x`, this relates outcome `y` to **covariates** `x`\n- `family`: the type of model (depends on the data type of the outcome)\n- `data`: a data.frame containing the columns named in `formula`\n:::\n\n## Bernoulli fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- glm(infected ~ social_contact, family = binomial(), data = infections)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = infected ~ social_contact, family = binomial(), \n    data = infections)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -2.3702     0.5739  -4.130 3.63e-05 ***\nsocial_contact   3.0933     0.8908   3.473 0.000515 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 128.21  on 99  degrees of freedom\nResidual deviance: 113.69  on 98  degrees of freedom\nAIC: 117.69\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\\\nWe wrote `family = binomial()`, but since `infected` is 0/1, the code knows to run a Bernoulli model.\n\n## Interpreting the fit\n\n- The estimates are on the **log-odds scale**, which isn't directly interpretable.\n\n- `plogis()` converts them to the **probability scale**:\n\n- This model is often called logistic regression, after the inverse logistic function (`plogis`).\n\n## Interpreting the fit\n\nAt social contact level `x`, the infection probability `≈ plogis(-2.37 + 3.09x)`\n\n- `x = 0` $\\implies$ `plogis(-2.37) ≈ 0.085`\n- `x = 0.5` $\\implies$ `plogis(-2.37 + 0.5 × 3.09) ≈ 0.24`\n- `x = 1` $\\implies$ `plogis(-2.37 + 1 × 3.09) ≈ 0.50`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = infected ~ social_contact, family = binomial(), \n    data = infections)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -2.3702     0.5739  -4.130 3.63e-05 ***\nsocial_contact   3.0933     0.8908   3.473 0.000515 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 128.21  on 99  degrees of freedom\nResidual deviance: 113.69  on 98  degrees of freedom\nAIC: 117.69\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n## Interpreting the fit\n\n- The **intercept** parameter controls the height of the curve at 0.\n- The **slope** parameter controls the rate of its increase as a function of $x$.\n\n![](images/intercept_plogis.png)\n\n## Interpreting the fit\n\n- The **intercept** parameter controls the height of the curve at 0.\n- The **slope** parameter controls the rate of its increase as a function of $x$.\n\n![](images/slope_plogis.png)\n\n## Interpreting the fit\n\n- `x = 0` $\\implies$ `plogis(-2.37) ≈ 0.085`\n- `x = 0.5` $\\implies$ `plogis(-2.37 + 0.5 * 3.09) ≈ 0.30`\n- `x = 1` $\\implies$ `plogis(-2.37 + 1 * 3.09) ≈ 0.67`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-bernoulli-overlay-1.png){width=768}\n:::\n:::\n\n\n## Aggregated (Binomial) data\n\nIf we only see **totals within categories**, then we can use a Binomial model.\n\n\\\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-infection-totals .cell}\n\n```{.r .cell-code}\ninfections_totals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  social_level not_infected infected total\n  <fct>               <dbl>    <dbl> <dbl>\n1 low                    29        6    35\n2 medium                 20        9    29\n3 high                   17       19    36\n```\n\n\n:::\n:::\n\n\n## Aggregated (Binomial) data\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-infection-totals-1.png){width=768}\n:::\n:::\n\n\n## Fitting the Binomial\n\nFor group-level counts, the formula's left-hand side becomes a proportion, and we add `weights` to reflect group totals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- glm(infected / total ~ social_level, family = binomial(),\n           weights = total, data = infections_totals)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = infected/total ~ social_level, family = binomial(), \n    data = infections_totals, weights = total)\n\nCoefficients:\n                   Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -1.5755     0.4485  -3.513 0.000443 ***\nsocial_levelmedium   0.7770     0.6019   1.291 0.196703    \nsocial_levelhigh     1.6868     0.5591   3.017 0.002554 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance:  1.0418e+01  on 2  degrees of freedom\nResidual deviance: -9.5479e-15  on 0  degrees of freedom\nAIC: 17.201\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n:::\n\n\n## Interpreting the fit\n\n![](images/binomial_fitted_probabilities.png)\n\n## Poisson Models\n\nThese models apply to **count data**.\n\nThe Poisson arises as the \"number of occurrences of an event that happens rarely\nbut has many opportunities to happen\" [@wiki_poisson_distribution]. The number\nof raindrops landing on a small window during a heavy storm would be Poisson\ndistributed.\n\n![](images/poisson_raindrop.png)\n\n## Poisson Models\n\nThese models apply to **count data**.\n\nThe Poisson arises as the \"number of occurrences of an event that happens rarely\nbut has many opportunities to happen\" [@wiki_poisson_distribution]. The number\nof raindrops landing on a small window during a heavy storm would be Poisson\ndistributed.\n\n![](images/poisson_histogram.png)\n\n## Poisson Models\n\nCounts can depend on sample characteristics. The rain may have been falling harder earlier in the night.\n\n![](images/poisson_histogram_sequence.png)\n\n## Poisson Models\n\nMany biological counts have this flavor:\n\n- Transcript counts\n    - Each transcript has a small chance of binding to cDNA, but there are many transcripts\n    - The number of transcripts of a gene might depend on drug treatment\n- Mutation count along a genome segment\n    - Each base pair has a small chance of being mutated, but there are many base pairs overall\n    - The number of mutations depends on selection pressure\n- Infection count within a county\n    - Each person has a small chance of being infected, but the population is large\n    - The infection rates decrease further from the epicenter\n\n## Outbreak counts vs. distance\n\nLet's fit a model for the infection count example.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-outbreak-mean-count-1.png){width=768}\n:::\n:::\n\n\n## Outbreak counts vs. distance\n\nCounts can depend on sample characteristics, like more infections in counties closer to the outbreak epicenter.\n\n\n::: {#tbl-outbreak-sample .cell}\n\n```{.r .cell-code}\noutbreak |>\n    select(sample_id, epicenter_distance, infected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 100 × 3\n   sample_id epicenter_distance infected\n   <chr>                  <dbl>    <dbl>\n 1 sample_1               0.952        0\n 2 sample_2               0.213        3\n 3 sample_3               0.498        3\n 4 sample_4               0.307        1\n 5 sample_5               0.888        1\n 6 sample_6               0.605        1\n 7 sample_7               0.930        1\n 8 sample_8               0.737        0\n 9 sample_9               0.399        0\n10 sample_10              0.104        5\n# ℹ 90 more rows\n```\n\n\n:::\n:::\n\n\n## Fitting the Poisson\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- glm(infected ~ epicenter_distance, family = poisson(), data = outbreak)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = infected ~ epicenter_distance, family = poisson(), \n    data = outbreak)\n\nCoefficients:\n                   Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         2.41503    0.09458   25.54   <2e-16 ***\nepicenter_distance -3.89306    0.27251  -14.29   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 364.28  on 99  degrees of freedom\nResidual deviance: 108.18  on 98  degrees of freedom\nAIC: 304.64\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\nThe output is on the **log scale**, so exponentiate before interpreting.\n\n## Interpreting the fit\n\nAt distance `x`, the average count is `≈ exp(2.4 - 0.5x)`\n\n- `x = 0` $\\implies$ `exp(2.4) ≈ 11.0`\n- `x = 0.5` $\\implies$ `exp(2.4 − 0.5 * 3.9) ≈ 1.6`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = infected ~ epicenter_distance, family = poisson(), \n    data = outbreak)\n\nCoefficients:\n                   Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         2.41503    0.09458   25.54   <2e-16 ***\nepicenter_distance -3.89306    0.27251  -14.29   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 364.28  on 99  degrees of freedom\nResidual deviance: 108.18  on 98  degrees of freedom\nAIC: 304.64\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n## Interpreting the fit\n\nAt distance `x`, the average count is `≈ exp(2.4 - 0.5x)`\n\n- `x = 0` $\\implies$ `exp(2.4) ≈ 11.0`\n- `x = 0.5` $\\implies$ `exp(2.4 − 0.5 × 3.9) ≈ 1.6`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-outbreak-overlay-1.png){width=960}\n:::\n:::\n\n\n## Linear Regression Models\n\nLinear regression applies when the response is **continuous**. For example:\n\n- Temperature\n- Antibody titre\n- Leaf width\n\nThe model assumes random Gaussian error around a mean value that depends on the covariates.\n\n## Gaussian Assumption\n\n![](images/regression_gsn_errors.png)\n\n## Antibody titre vs age\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-antibody-age-1.png){width=768}\n:::\n:::\n\n\n## Fitting with `lm`\n\nSame inputs as `glm`, but no `family`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(antibody ~ age, data = antibody)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = antibody ~ age, data = antibody)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-5.345 -1.076 -0.076  1.325  6.698 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 19.57687    0.49545  39.514  < 2e-16 ***\nage          0.05834    0.01041   5.606 1.91e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.205 on 98 degrees of freedom\nMultiple R-squared:  0.2428,\tAdjusted R-squared:  0.2351 \nF-statistic: 31.42 on 1 and 98 DF,  p-value: 1.911e-07\n```\n\n\n:::\n:::\n\n\n## Interpreting the fit\n\nThe estimates are on the same scale as the response, so we can interpret the\nresults directly.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = antibody ~ age, data = antibody)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-5.345 -1.076 -0.076  1.325  6.698 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 19.57687    0.49545  39.514  < 2e-16 ***\nage          0.05834    0.01041   5.606 1.91e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.205 on 98 degrees of freedom\nMultiple R-squared:  0.2428,\tAdjusted R-squared:  0.2351 \nF-statistic: 31.42 on 1 and 98 DF,  p-value: 1.911e-07\n```\n\n\n:::\n:::\n\n\nPredicted titre at age `x` is `19.6 + 0.058x`\n\nE.g. at age 10 the prediction is `≈ 19.6 + 0.58 = 20.18`\n\n## Why Gaussian errors?\n\nThe **Central Limit Theorem**: the average of many small, independent effects tends toward a Gaussian distribution.\n\nWe implicitly assume many small, independent factors other than age that perturb the observed antibody measurement.\n\n![](images/regression_gsn_clt.png)\n\n## Discussion {.your-turn}\n\n_Recommend a model for each of the following questions. What plot would you use to validate your choice? What would be the response and covariate variables?_\n\n- Does the proportion of Lactobacillus in a 16S sequencing dataset change between treatment and control groups in an RCT?\n- We have counts of gene transcripts over time from a bulk RNA-sequencing experiment. Is its expression systematically changing?\n- Study participants have been grouped into low and high inflammation groups. We want to see whether abundance of a given microbe-produced metabolite is associated with inflammation group.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_619f890e\" minutes=\"5\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Variations: Multiple Predictors, Mixed Effects, Interactions\n\n## Multiple Predictors\n\nFormulas can have multiple covariates: `y ~ x1 + x2`\n\nEach estimate is the effect of a variable **with all others held fixed**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(antibody ~ age + blood_pressure, data = antibody)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = antibody ~ age + blood_pressure, data = antibody)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-5.014 -1.044 -0.175  1.288  6.525 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    21.10179    1.10078  19.170  < 2e-16 ***\nage             0.05839    0.01033   5.650 1.61e-07 ***\nblood_pressure -0.01553    0.01003  -1.549    0.125    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.19 on 97 degrees of freedom\nMultiple R-squared:  0.2611,\tAdjusted R-squared:  0.2458 \nF-statistic: 17.14 on 2 and 97 DF,  p-value: 4.239e-07\n```\n\n\n:::\n:::\n\n\n\n::: {style=\"font-size: 0.9em\"}\n*Fixing blood pressure, average antibody level increases by 0.058 units per year of age.*\n:::\n\n## Multiple Predictors\n\n![](images/two_predictors_3d.png)\n\n## Multiple Predictors\n\n![](images/two_predictors_2d.png)\n\n## Categorical covariates\n\nAll models can be used with covariates that are categorical. They are not\nlimited to drawing smooth curves or straight lines.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/gsn-categories-1.png){width=960}\n:::\n:::\n\n\n## Categorical covariates\n\nThis is a linear regression model fitted to the previous slide's data, where\nantibody levels are grouped.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = antibody ~ age_group, data = antibody_grouped)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-5.209 -1.311  0.119  1.429  6.025 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        20.6901     0.4078  50.737  < 2e-16 ***\nage_group(30,60]    1.3476     0.5376   2.507   0.0139 *  \nage_group(60,100]   2.9923     0.5977   5.006 2.48e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.27 on 97 degrees of freedom\nMultiple R-squared:  0.2054,\tAdjusted R-squared:  0.189 \nF-statistic: 12.54 on 2 and 97 DF,  p-value: 1.436e-05\n```\n\n\n:::\n:::\n\n\n## Mixed effects\n\n- Baseline effects often **vary across contexts**.\n\n- In the Bernoulli example, the way infection probability increases with social\ncontact may vary across counties due to unmeasured factors, like population\ndensity.\n\n## County-varying baselines\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-county-baselines-1.png){width=864}\n:::\n:::\n\n\n## Random effects\n\n- We could add county as an ordinary covariate — but with many counties, this becomes unwieldy.\n- A better approach is to use a **random effect**\n- We imagine county effects as draws from a shared distribution.\n\n![](images/random_effects_counties.png)\n\n\n## Random effects\n\n- We estimate the **overall variation across counties**, not each one separately.\n- This is statistically easier, so it yields higher power.\n- Because they include both fixed and random effects, these are called **mixed effects** models.\n\n![](images/random_effects_counties.png)\n\n## Fitting with `glmer`\n\nReplace `glm` with `glmer` and add `(1 | county)` to the formula.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- glmer(infected ~ social_contact + (1 | county),\n             family = binomial(), data = mixed_effect_data)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized linear mixed model fit by maximum likelihood (Laplace\n  Approximation) [glmerMod]\n Family: binomial  ( logit )\nFormula: infected ~ social_contact + (1 | county)\n   Data: mixed_effect_data\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n    230.8     240.7    -112.4     224.8       197 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.2664 -0.6116 -0.3655  0.7618  2.5619 \n\nRandom effects:\n Groups Name        Variance Std.Dev.\n county (Intercept) 0.5015   0.7082  \nNumber of obs: 200, groups:  county, 10\n\nFixed effects:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -2.4680     0.4783  -5.160 2.47e-07 ***\nsocial_contact   3.5811     0.6886   5.201 1.99e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\nsocil_cntct -0.808\n```\n\n\n:::\n:::\n\n\n## Interpreting the random effect\n\nThe `SD` says the intercept varies by roughly 0.71 across counties, at any level\nof social contact. Therefore, even at social contact = 0, the infection\nprobabilities below would both be typical:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplogis(-2.28 - 2 * 0.71)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02412702\n```\n\n\n:::\n\n```{.r .cell-code}\nplogis(-2.28 + 2 * 0.71)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2973393\n```\n\n\n:::\n:::\n\n\n## Interactions\n\nSometimes the effect of a variable on the response **depends on the value of\nother variables**. This is called an interaction.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/plot-interaction-pattern-1.png){width=672}\n:::\n:::\n\n\n## Interaction syntax\n\nUse `y ~ x1 + x1 : x2` — meaning the `x1` effect depends on the level of `x2`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(antibody ~ age + age : group, data = interaction_data)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = antibody ~ age + age:group, data = interaction_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.4765 -1.6597 -0.0768  1.5193  6.1728 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       0.543777   0.300945   1.807   0.0723 .  \nage               0.061801   0.007332   8.428 7.31e-15 ***\nage:grouphealthy -0.002380   0.006885  -0.346   0.7300    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.158 on 197 degrees of freedom\nMultiple R-squared:  0.293,\tAdjusted R-squared:  0.2858 \nF-statistic: 40.82 on 2 and 197 DF,  p-value: 1.47e-15\n```\n\n\n:::\n:::\n\n\n\n::: {style=\"font-size: 0.9em\"}\n- Healthy group: titre rises by **0.062** per year of age\n- Disease group: titre rises by **0.062 - 0.002** per year (sum the two rows)\n:::\n\n## Variations recap\n\n- Although we introduced these with Bernoulli and linear regression examples, they apply to any of the models we've seen.\n\n- They are the key tools we can use when **revising a model's working assumptions** to improve its fit.\n\n## Discussion {.your-turn}\n\nThink through the first three parts of the modeling checklist for a\ndataset that you are interested in from your own work or study.\n\n1. **Biological Question**. What real-world questions do you want to answer?\n\n2. **Plot the Data.** Did you ever plot the data? If so, what patterns did you see? If not, what plots could you make?\n\n3. **Working Assumptions.** Make a small-world story about your data. What model type, response $y$, and covariates $x$ could you use?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_2c56e54d\" minutes=\"5\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n\n# Part 3: Case Studies\n\n## Case Study: Longitudinal Cytokines\n\n**Biological Question**\n\n> Does treatment with the anti-inflammatory drug change cytokine concentrations post-treatment (week 1), and if so does the effect persist into the long run (week 7)?\n\n## Plot the data\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/load-cytokines-all-1.png){width=1152}\n:::\n:::\n\n\nThere seems to be a strong treatment effect at one week that weakens by\nweek 7. We'll focus on **IL-1a**, the cytokine with the fewest measurements\nbelow the detection limit.\n\n## Working assumptions\n\n::: incremental\n- Luminex gives a **continuous** readout → linear regression\n- Many small, unrelated factors perturb the measurement → **Gaussian error**\n- Errors are likely multiplicative, not additive → model **log-concentration**\n:::\n\n## A first model\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncytokines <- cytokines |> filter(cytokine == \"IL-1a\")\nfit <- lm(log(conc) ~ arm, data = cytokines)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(conc) ~ arm, data = cytokines)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.8298 -0.7570 -0.0689  0.6711  3.7742 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    4.4001     0.1276  34.486  < 2e-16 ***\narmtreatment  -1.2410     0.1847  -6.719 5.18e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.06 on 130 degrees of freedom\nMultiple R-squared:  0.2578,\tAdjusted R-squared:  0.2521 \nF-statistic: 45.15 on 1 and 130 DF,  p-value: 5.176e-10\n```\n\n\n:::\n:::\n\n\nThe treatment effect is significant, but we should interpret a model only after\nchecking its fidelity.\n\n## Check by simulation\n\nThe `simulate` function lets you simulate new response values. By default each\nsimulated output matches the corresponding training sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulate(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        sim_1\n1   2.9782474\n2   6.0056472\n3   4.6327290\n4   3.7430813\n5   3.5097814\n6   5.1458344\n7   4.5135263\n8   5.1387133\n9   4.4975827\n10  4.5481366\n11  6.4344731\n12  2.8556228\n13  4.9953841\n14  2.0500680\n15  4.0052839\n16  5.4021195\n17  3.6101001\n18  4.5343215\n19  4.8250682\n20  4.5887460\n21  3.7720848\n22  4.5184610\n23  2.6803282\n24  4.6261843\n25  3.4404870\n26  3.3533365\n27  2.4449162\n28  3.5283287\n29  3.4626330\n30  2.2391925\n31  2.9518091\n32  1.9920836\n33  2.1450500\n34  4.6969986\n35  6.6768738\n36  3.3847478\n37  5.7555652\n38  3.9405248\n39  4.3984729\n40  5.1203345\n41  3.5206530\n42  4.6858492\n43  4.7225900\n44  4.0776217\n45  3.8196220\n46  4.3564437\n47  4.2561353\n48  5.0029103\n49  3.9887328\n50  3.7775043\n51  3.0674642\n52  3.0946751\n53  2.9118487\n54  4.0622687\n55  5.7886975\n56  5.0469376\n57  4.6218549\n58  4.4094212\n59  2.5883835\n60  3.6234321\n61  4.7350077\n62  3.9779685\n63  3.5437505\n64  4.1855129\n65  3.2432183\n66  5.0063909\n67  3.9797440\n68  4.6439749\n69  4.5911723\n70  4.0344294\n71  5.5723322\n72  4.9410032\n73  1.5954450\n74  2.1826993\n75  4.5523856\n76  4.2886943\n77  2.2728754\n78  4.2109297\n79  3.6347512\n80  4.4969185\n81  2.1934358\n82  4.2587041\n83  3.5371852\n84  1.3782517\n85  3.3798805\n86  2.9604233\n87  4.0369129\n88  5.7988303\n89  3.8604942\n90  3.1895635\n91  4.7362505\n92  4.1814273\n93  5.0781209\n94  3.2112666\n95  3.1003526\n96  4.8286527\n97  3.4191788\n98  3.0124659\n99  3.3845371\n100 4.0511941\n101 5.2224927\n102 5.1819689\n103 5.1883101\n104 4.3829128\n105 4.5848620\n106 5.1636166\n107 4.2656986\n108 5.5124452\n109 2.5322445\n110 2.2851774\n111 3.7349694\n112 4.1399135\n113 2.8860256\n114 4.4688755\n115 3.9835402\n116 3.2328957\n117 2.3437614\n118 2.0541907\n119 3.2562084\n120 0.2153196\n121 3.3757924\n122 4.6326766\n123 4.9712758\n124 4.0738577\n125 6.0081757\n126 4.2066597\n127 3.8932396\n128 4.4853314\n129 3.4849389\n130 4.0478774\n131 2.6657909\n132 4.7393394\n```\n\n\n:::\n:::\n\n\n## Check by simulation\n\nThe `simulate_cytokines` helper function runs `simulate` and reshapes the data\nfor plotting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_data <- simulate_cytokine(fit)\nplot_cytokine(sim_data)\n```\n\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/sim-check-main-effect-1.png){width=864}\n:::\n:::\n\n\n## What went wrong?\n\n::: incremental\n- ✅ Overall concentrations are in the correct range\n- ✅ Control group has larger concentrations than treatment\n- ❌ In the real data, **most blue curves decrease at week 1**\n- ❌ In the simulation, about **half the curves increase**\n:::\n\n## Revising the model\n\n- We gave the model **no temporal information**. We could fix this with the formula: `log(conc) ~ arm + time_point`.\n\n   - This data story isn't reasonable either\n   - We don't expect IL-1a concentration to change just because the clock reads week 1 or 7.\n\nWe want the **treatment effect itself to depend on the week**, a type of interaction: `log(conc) ~ arm + arm : time_point`.\n\n## Fitted interaction model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(log(conc) ~ arm + arm : time_point, data = cytokines)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(conc) ~ arm + arm:time_point, data = cytokines)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.36776 -0.57246  0.00535  0.47567  2.64101 \n\nCoefficients:\n                              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     4.6636     0.1718  27.147  < 2e-16 ***\narmtreatment                   -0.2855     0.2487  -1.148   0.2531    \narmplacebo:time_pointweek_1    -0.4784     0.2429  -1.969   0.0511 .  \narmtreatment:time_pointweek_1  -2.3398     0.2543  -9.203 9.50e-16 ***\narmplacebo:time_pointweek_7    -0.3121     0.2429  -1.285   0.2013    \narmtreatment:time_pointweek_7  -1.3173     0.2543  -5.181 8.51e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.8239 on 126 degrees of freedom\nMultiple R-squared:  0.5653,\tAdjusted R-squared:  0.5481 \nF-statistic: 32.77 on 5 and 126 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Interpreting the coefficients\n\nExpected log-concentrations:\n\n::: {style=\"font-size: 0.9em\"}\n- Placebo at baseline: 4.66\n- Treatment at baseline: 4.66 − 0.29\n- Placebo at week 1: 4.66 − 0.48\n- Treatment at week 1: 4.66 − 2.34\n- ...\n:::\n\n\nThe large negative coefficient for `armtreatment:time_pointweek_1` captures our earlier observation that the treatment effect is strongest at week 1.\n\n## Simulate updated model\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/sim-check-interaction-model-1.png){width=864}\n:::\n:::\n\n\n## Mixed-effects version\n\nThe model treats each sample as independent, but measurements from the same participant are dependent.\n\n- Dependence reduces the effective sample size.\n- We can add a participant-level random effect to introduce dependence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lmer(log(conc) ~ arm + arm : time_point + (1 | pid), data = cytokines)\n```\n:::\n\n\n## Simulate updated model\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](slides_files/figure-revealjs/sim-check-mixed-effects-1.png){width=864}\n:::\n:::\n\n\n## Model results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: log(conc) ~ arm + arm:time_point + (1 | pid)\n   Data: cytokines\n\nREML criterion at convergence: 327.2\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.8408 -0.6889 -0.0017  0.5540  3.1092 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n pid      (Intercept) 0.02198  0.1483  \n Residual             0.65679  0.8104  \nNumber of obs: 132, groups:  pid, 44\n\nFixed effects:\n                              Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)                     4.6636     0.1718 125.7363  27.147  < 2e-16 ***\narmtreatment                   -0.2855     0.2487 125.7363  -1.148   0.2531    \narmplacebo:time_pointweek_1    -0.4784     0.2390  83.9999  -2.002   0.0485 *  \narmtreatment:time_pointweek_1  -2.3398     0.2501  83.9999  -9.355 1.14e-14 ***\narmplacebo:time_pointweek_7    -0.3121     0.2390  83.9999  -1.306   0.1952    \narmtreatment:time_pointweek_7  -1.3173     0.2501  83.9999  -5.267 1.05e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) armtrt armp:__1 armt:__1 armp:__7\narmtreatmnt -0.691                                  \narmplcb:__1 -0.696  0.481                           \narmtrtm:__1  0.000 -0.503  0.000                    \narmplcb:__7 -0.696  0.481  0.500    0.000           \narmtrtm:__7  0.000 -0.503  0.000    0.500    0.000  \n```\n\n\n:::\n:::\n\n\n## Interpretation\n\n- Visually, the model doesn't seem much better.\n- Participant variation (SD **0.15**) is small vs. measurement error (**0.81**).\n- But it's the safer model in practice. By accounting for within-participant dependence, we're being honest about the effective sample size.\n\n# Wrapping Up\n\n## What we did today\n\n::: {.incremental style=\"font-size: 0.95em\"}\n1. Models as **data stories** — small world vs. large world.\n2. A **modeling checklist** to guide our work: question → plot → assumptions → checks → revise.\n3. A tour through the **model zoo**: Bernoulli, Binomial, Poisson, Linear.\n4. **Variations** for complex data: multiple predictors, mixed effects, interactions.\n5. **Case study** illustrating the checklist\n:::\n\n## Exercise 2 {.your-turn}\n\nOpen `notebooks/05-modeling.qmd` in your Codespace.\n\n<br>\n\nThe modes flip: whoever was agentic in Exercise 1 is manual now, and vice versa.\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<countdown-timer class=\"countdown\" id=\"timer_49d26555\" minutes=\"30\" seconds=\"0\" update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\"></countdown-timer>\n```\n\n:::\n:::\n\n",
    "supporting": [
      "slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/countdown-0.6.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/countdown-0.6.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}